apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nodejs
  namespace: argocd
spec:
  project: project-dev   #  IMPORTANT (must match AppProject name)

  source:
    repoURL: https://github.com/mohamed1311990/nodejs.git #repo
    targetRevision: dev  # branch
    path: nodejs-app  #kubernetes manifests 
    helm:
      releaseName: nodejs-dev
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-nodejs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
